default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: unter_challange_development

test:
  <<: *default
  database: unter_challange_test

production:
  <<: *default
  database: unter_challange_production
  username: unter_challange
  password: <%= ENV['UNTER_CHALLANGE_DATABASE_PASSWORD'] %>
